" Wraps paths to make them relative to this directory.
function! Dot(path)
  return '~/.vim/config/' . a:path
endfunction

let configs = [
  \'basic.vim'
\]
  " \'filetypes.vim',
  " \'colors.vim'

" Load all configuration modules.
for file in configs
  execute 'source' Dot(file)
endfor

" Lua file configurations
lua require('lua/plugins')
lua require('lua/lsp')
