# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Configure Bash History
export HISTCONTROL=ignoreboth:erasedups

# User specific aliases and functions

for file in ~/dotfiles/{path,exports,aliases,functions,extra}.bashrc; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;

unset file

